# Generated by Django 4.1 on 2022-08-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_indication_plague_plaguecategory_pricelist_voucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='job_center',
        ),
    ]
